// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // El CLI (migrate/introspect/studio) usa la conexión DIRECTA (sin pgbouncer)
  // de Neon: el pooler de Neon corre en modo transacción y no soporta los
  // advisory locks que Prisma Migrate necesita. La app en tiempo de
  // ejecución usa DATABASE_URL (pooled) — ver src/lib/db/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
